### ISSUE TITLE
Cannot use babel-eslint config in package.json

### ISSUE THREAD

**Issue by xeoneux** [KidkArolis/healthier#19]
First of all, really love the concept of healthier for linting 👍 

When I try linting `jsx` files, it doesn't parse them using `babel-eslint` in **VS Code**

```json
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "healthier": "^2.0.0"
  },
  "healthier": {
    "parser": "babel-eslint"
  }
```

**Comment by KidkArolis** [comment]
Strange, I just tried this and couldn't reproduce the issue.

Are you using Healthier Linter 2.0.0 in VSCode?
<img width="245" alt="image" src="https://user-images.githubusercontent.com/324440/52163561-9f129800-26db-11e9-900b-bd689c3118c3.png">

With that package.json, I'm seeing:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/324440/52163573-b8b3df80-26db-11e9-96cd-912eee849311.png">

If I remove parser from package.json#parser, I get invalid syntax error instead:
<img width="495" alt="image" src="https://user-images.githubusercontent.com/324440/52163580-ccf7dc80-26db-11e9-9ed8-12127b7dc729.png">

The reason this _should_ be working is because VSCode plugin calls `require('healthier').lintTextSync()` which takes into account all of your package.json options .

**Comment by KidkArolis** [comment]
@xeoneux did you have a chance to double check the version of the VSCode extension?

**Comment by xeoneux** [comment]
Hey, sorry for not updating the issue.
It started working as soon as I added `babel-eslint` to dev deps. :smile:

**Comment by KidkArolis** [comment]
Nice one, thanks for closing!
