### ISSUE TITLE
react/jsx-indent errors keep happening

### ISSUE THREAD

**Issue by sheerun** [KidkArolis/healthier#23]
I use following:

    "eslint": "^5.6.1",
    "eslint-config-healthier": "^1.0.0",

Then:

    "extends": ["healthier", "healthier/react"],

I get following errors:

node_modules/.bin/eslint .

./search/components/unit/index.js
  80:15  error  Expected indentation of 16 space characters but found 14  react/jsx-indent

Here's example file to reproduce formatted with prettier-standard:

```
import React from 'react'

class Select extends React.Component {
  render () {
    return (
      <div className='select'>
        <select name='rooms'>
          {this.state.kind === 'flat'
            ? [1, 2, 3].map(value => (
                <option key={value} value={value}>
                  {value}
                </option>
              ))
            : [1, 2, 3, 4].map(value => (
                <option key={value} value={value}>
                  {value}
                </option>
              ))}
        </select>
      </div>
    )
  }
}

export default Select
```

**Comment by KidkArolis** [comment]
Fixed in 1.0.2, the issue was interesting, because of my hacky merging and renaming things, standard-react in turn extends standard-jsx which was bringing in a lot of react/* rules that were actually already imported.

So lints correctly with eslint now.

But I realised something else, that .eslintrc for `healthier` (not the eslint config, but the cli tool) is not very useful for extending, because if you extend anything that has styling rules, e.g. `eslint-config-standard-react`, then things won't lint again. Maybe one "fix" would be to somehow always append healthier's prettier rules that turn off styling after whatever you extended. In general, this wouldn't be an issue, but it is a pretty prominent issue for react rules specifically. I guess this is a bit related to whether healthier should go beyond what standard does by default (I think so? given that standard is not really maintaining react rules anyway, so we could start doing it here).

Also, after playing with healthier for a couple weeks, started wondering if eslint should just get a special flag, `--no-style` where it automatically excludes all style rules (basically all fixable rules). This kind of would almost eliminate the need for healthier. Or maybe not, cause it's also about an opinionated set of things in a single package as much as about turning styling rules off.
