### ISSUE TITLE
Support prettier-standard

### ISSUE THREAD

**Issue by sheerun** [KidkArolis/healthier#8]
Hello,

It would be nice if you supported standard.js community and supported prettier-standard which is an equivalent of prettier. I think the easiest way to support if would be to drop healthier dependency on prettier and focus on linting code instead of formatting it.

**Comment by KidkArolis** [comment]
Haven't read your other issues yet, will do so in a moment.

But initial thoughts are that you can already use prettier-standard with healthier and it would work the same way, so instead of:

```
{
  "name": "my-cool-package",
  "devDependencies": {
    "healthier": "*",
    "prettier": "*"
  },
  "scripts": {
    "test": "healthier && ava",
    "format": "prettier --write '**/*.{js,json,css}'"
  }
}
```

you would do

```
{
  "name": "my-cool-package",
  "devDependencies": {
    "healthier": "*",
    "prettier-standard": "*"
  },
  "scripts": {
    "test": "healthier && ava",
    "format": "prettier-standard --write '**/*.{js,json,css}'"
  }
}
```

So it's actually quite compatible already.

The only caveats are I guess:

1. Wasteful extra dependency on prettier in this case installed by healthier (maybe it's ok.. healthier installs quite quickly)
2. Running `healthier --fix` runs prettier which is a bit confusing in this case (perhaps I could auto detect if prettier-standard is installed)
3. Docs mention prettier a lot (I could add a section in the README about prettier-standard, so that people have a clearer choice, especially since healthier is basically standard anyway)

Hm, thinking further.. in my head, the idea was that you would chooe to either use `prettier/healthier` _or_ `prettier-standard/standard`? What is an advantage of using `prettier-standard/healthier`?

And having said all that, yeah, I'm a little bit intrigued by the idea of dropping the formatting.. Then this is more of pure linter, this built in `--fix` is cute, but cute things can be bad..

This answer is getting long, but do you know if any of the non style formatting eslint rules used in standard are fixable? That is, if I remove prettier formatting, does `--fix` still make sense?

**Comment by sheerun** [comment]
There's no prettier-standard/standard, it's someone's else package. prettier-standard doesn't need eslint-config-prettier-standard. Also prettier-standard fully supports `.prettierrc`

I think it would be better if healthier dropped `--fix` and left formatting for other tools, be it prettier-standard or prettier. I would save dependency and don't favor one style of formatting over another.

**Comment by sheerun** [comment]
Also there's another issue, because you need to keep up updatting prettier dependency in this repository. What will happen if someone specifies "prettier": "^1.16.0" in their repository is that two versions of prettier will be installed. So the issue is not only with prettier-standard but also with prettier itself.

**Comment by KidkArolis** [comment]
To clarify, I meant, there are the following combos possible:

1. you use `prettier` together with `healthier` - works well
2. you use `prettier-standard` with `standard` - should work well, no?
3. you are suggesting to use `prettier-standard` with `healthier` - what's the advantage of doing this, instead of just doing Option 2?

But yes, I'm coming around to the idea of removing formatting althogether to make it agnostic to what you use. Are there other formatters though? In addition to prettier, prettierx and prettier-standard (all of which are already compatible with healthier anyway)? Although I might keep `--init` feature in ;) to give you an opinionated .prettierrc, since that's something that's useful to me..

**Comment by sheerun** [comment]
As for 2. it's not possible because `standard` has slightly different whitespace formatting rules than prettier-standard (mostly bugs and trenary oprator), and it cares about whitespace formatting so you need to create custom .eslintrc that extends `prettier` and `prettier/standard`..

**Comment by sheerun** [comment]
I'm fine with `--init` because prettier-standard and prettierx support `.prettierrc`. My only issue is with specifying prettier as dependency of healthier because it would download duplicate dependency when:

1. someone uses prettier-standard or prettierx
2. when someone wants to use different version of prettier than is shipped with healthier

**Comment by sheerun** [comment]
besides you already show in the readme that prettier should be in dependencies

**Comment by sheerun** [comment]
I don't think so, plus prettier handles slightly more than whitespace rules for example:

```
echo '(foo) => {}' | prettier --stdin --parser babylon
foo => {};
```

so it not only formats whitespace but e.g. removes parenthesis and adds semicolon

Additionaly any non-whitespace refactorings are usually not safe.. even changing `==` to `===` can have unforseen consequences. I think it would be reasonable to remove `--fix` and re-introduce it only if you are sure it is useful

**Comment by KidkArolis** [comment]
There are good reasons to remove --fix altogether and direct dependency on prettier.

I'll paste the reasoning later from gitter.

But the decision is to: remove --fix, remove prettier, always use prettier directly. Healthier becomes formatter independent code quality checker.
